# Generated by Django 4.1.7 on 2023-03-26 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLoginLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text='The email address used for the login attempt.', max_length=255, verbose_name='email')),
                ('is_successful', models.BooleanField(default=True, help_text='True denotes that the login was successful')),
                ('attempted_time', models.DateTimeField(auto_now_add=True, verbose_name='time attempted')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='The IP from which the login was attempted', null=True, verbose_name='IP address')),
                ('browser', models.CharField(blank=True, help_text='The browser used to login', max_length=30, null=True, verbose_name='browser')),
            ],
            options={
                'verbose_name': 'User Login Log',
                'verbose_name_plural': 'User Login Logs',
                'ordering': ('-id',),
            },
        ),
    ]
