name: CI workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]


jobs:
  build:
    runs-on: ubuntu-latest
    container: python:3.9-slim
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # this Action should follow steps to set up Python build environment
      - name: Install Python dependencies
        uses: py-actions/py-dependency-install@v4
        with:
          update-pip: "true"
          update-setuptools: "false"
          update-wheel: "false"
          path: "requirements/local.txt"

#      - name: Lint with flake8
#        run: |
#          flake8 service --count --select=E9,F63,F7,F82 --show-source --statistics
#          flake8 service --count --max-complexity=10 --max-line-length=127 --statistics

#      - name: Show repo env secret
#        run: |
#            echo ${{ secrets.ALLOWED_HOSTS }}
#            echo ${{ env.ALLOWED_HOSTS }}

#      - name: Run unit tests with Pytest
#        run: |
#          echo $SECRET_KEY
#          pytest
