# Generated by Django 4.1.7 on 2023-12-24 08:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(help_text='Unique reference by the user within the tenant', max_length=128)),
                ('is_active', models.BooleanField(default=True, help_text='if TRUE the record is available')),
                ('name', models.CharField(help_text='Name of product.', max_length=256)),
                ('short_description', models.TextField(blank=True, default='', help_text='Short summary, can be used in search results.')),
                ('long_description', models.TextField(blank=True, default='', help_text='Long Description')),
                ('valid_from', models.DateTimeField(blank=True, help_text='Enter the datetime from which the product is valid', null=True, verbose_name='Valid from')),
                ('valid_until', models.DateTimeField(blank=True, help_text="Enter the datetime on which the product's validity expires", null=True, verbose_name='Valid until')),
                ('pre_order', models.BooleanField(default=False, help_text='Can be pre ordered', verbose_name='Product is a pre-order product')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['code'], name='products_pr_code_4c2607_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['code', 'is_active'], name='products_pr_code_a51b6e_idx'),
        ),
    ]
